### ISSUE TITLE
Memory Errors 

### ISSUE THREAD

**Issue by nbardy** [bitclout/mongodb-dumper#4]
```
I0521 00:42:26.033010       1 server.go:1171] Server._handleBlock: Received block ( 9113 / 26259 ) from Peer [ Remote Address: 35.232.92.5:17000 PeerID=2 ]
I0521 00:42:26.035622       1 server.go:1171] Server._handleBlock: Received block ( 9114 / 26259 ) from Peer [ Remote Address: 35.232.92.5:17000 PeerID=2 ]
I0521 00:42:26.038999       1 server.go:1171] Server._handleBlock: Received block ( 9115 / 26259 ) from Peer [ Remote Address: 35.232.92.5:17000 PeerID=2 ]
I0521 00:42:26.041663       1 server.go:1171] Server._handleBlock: Received block ( 9116 / 26259 ) from Peer [ Remote Address: 35.232.92.5:17000 PeerID=2 ]
I0521 00:42:26.044529       1 server.go:1171] Server._handleBlock: Received block ( 9117 / 26259 ) from Peer [ Remote Address: 35.232.92.5:17000 PeerID=2 ]
I0521 00:42:26.046986       1 server.go:1171] Server._handleBlock: Received block ( 9118 / 26259 ) from Peer [ Remote Address: 35.232.92.5:17000 PeerID=2 ]
I0521 00:42:26.049883       1 server.go:1171] Server._handleBlock: Received block ( 9119 / 26259 ) from Peer [ Remote Address: 35.232.92.5:17000 PeerID=2 ]
I0521 00:42:26.052300       1 server.go:1171] Server._handleBlock: Received block ( 9120 / 26259 ) from Peer [ Remote Address: 35.232.92.5:17000 PeerID=2 ]
Completed MongoDB BulkWrite.
Completed MongoDB BulkWrite.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xad9636]

goroutine 274 [running]:
github.com/bitclout/core/lib.HashToBigint(0x0, 0xd7ffffffffffffff)
        /bitclout/src/core/lib/miner.go:366 +0x36
github.com/bitclout/core/lib.(*BlockHash).String(0x0, 0xc09c3066f0, 0xf0b7cf)
        /bitclout/src/core/lib/network.go:53 +0x2f
github.com/bitclout/mongodb-dumper/mongodb.SimplifyMap(0xc09d34b830)
        /bitclout/src/mongodb-dumper/mongodb/sync_service.go:107 +0x1af2
github.com/bitclout/mongodb-dumper/mongodb.BadgerItrToJSON(0xc09a241360, 0x0, 0x0, 0x1)
        /bitclout/src/mongodb-dumper/mongodb/sync_service.go:455 +0x34c6
github.com/bitclout/mongodb-dumper/mongodb.(*SyncingService).Start.func1(0xc09d2f7000, 0x0, 0x0)
        /bitclout/src/mongodb-dumper/mongodb/sync_service.go:832 +0x1ee
github.com/dgraph-io/badger/v3.(*DB).View(0xc000589800, 0xc056513fa0, 0x0, 0x0)
        /root/go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2011.1/txn.go:800 +0x95
github.com/bitclout/mongodb-dumper/mongodb.(*SyncingService).Start(0xc05447a1c0)
        /bitclout/src/mongodb-dumper/mongodb/sync_service.go:803 +0xe6
github.com/bitclout/mongodb-dumper/cmd.(*Node).Start.func1(0xc05447c240)
        /bitclout/src/mongodb-dumper/cmd/node.go:33 +0x3f
created by github.com/bitclout/mongodb-dumper/cmd.(*Node).Start

````

I'm getting a crash from memory errors around block 9000. I

**Comment by bluepartyhat** [comment]
Thanks for reporting this. I'll try and repro in the coming days and look into it. I originally made this script for debugging testnets so it's possible things fell through the cracks.
